name: gss
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor:
  fluttertoast:
  flutter_bloc:
  flutter_svg:
  conditional_builder_null_safety:
  email_validator:
  flutter_localizations:
    sdk: flutter
  intl: any
  sizer:
  #di
  get_it:
  internet_connection_checker:
  #either
  dartz:
  #retrofit
  dio:
  retrofit:
  #dio show response
  pretty_dio_logger:
  hive:
  hive_flutter:
  path_provider:
  #firebase
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  flutter_phoenix:
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator:
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/svg/
     - assets/png/
#flutter_intl:
#  enabled: true # Required. Must be set to true to activate the plugin. Default: false
#  class_name: S # Optional. Sets the name for the generated localization class. Default: S
#  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
